- name: Prepare MicroK8s on all nodes
  hosts: all
  become: yes
  tasks:
    - name: Add user to MicroK8s group
      user:
        name: "{{ ansible_user }}"
        groups: microk8s
        append: yes
    - name: Install necessary packages
      apt:
        name:
          - nfs-common
          - btop
          - ipvsadm
        state: present
        update_cache: yes
